---
- name: Add some address objects to the firewall
  hosts: all
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  
  tasks:
    - name: Grab the credentials from ansible-vault
      include_vars: vars.yml
      no_log: 'yes'

    - name: Create address object
      panos_address_object:
        provider: '{{ provider }}'
        name: 'Test-Addr'
        value: '1.1.1.1/32'
        description: 'Test Address Object'
        commit: no
        tag: []

