# Tested working with PANTools 2019-09, Ansible 2.8.5, Python 3.7.4, Galaxy v2.2.3

- name: Demonstrate how to use OP module to execute various op commands on PANW device
  hosts: all
  connection: local
  gather_facts: False

  collections:
    - PaloAltoNetworks.paloaltonetworks
#  roles:
#    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - include_vars: 'vars.yml'
    no_log: 'yes'

  - name: Show system info op command
    panos_op:
      provider: '{{ provider }}'
      cmd: 'show system info'
    register: result

  - name: returned output in the default JSON format
    debug: msg='{{ result.stdout }}'
  - name: returned output in the XML format
    debug: msg='{{ result.stdout_xml }}'
